### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method 'NgModule'

### ISSUE THREAD

**Issue by gaurav112** [andrucz/ionic2-rating#1]
Cannot backtrack the error as the only message I get is this

```
Uncaught TypeError: Object #<Object> has no method 'NgModule', http://192.168.0.11:8100/build/js/app.bundle.js, Line: 100238
```

**Comment by andrucz** [comment]
Which version of Angular are you using?
For rc4 (ionic beta 11), use 0.0.6 ionic2-rating version. The latest version is made for ionic 2 rc.0 (angular 2 rc5).

**Comment by gaurav112** [comment]
0.0.6 worked. Thanks

**Comment by andrucz** [comment]
Nice. I'll update installation instructions.
