### ISSUE TITLE
why cant change rate with mouse

### ISSUE THREAD

**Issue by jyj545** [andrucz/ionic2-rating#11]
rt,i used the ionic2-rating and cant change rate number with mouse,does some thing different whit your code?
ionic info

Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed

    <rating [(ngModel)]="rate" 
        readOnly="false"
        max="5"
        (ngModelChange)="onModelChange($event)" (onKeyDown)="onKeyDownChange($event)"></r

**Comment by andrucz** [comment]
What version of ionic2-rating are you using?
Please check browser console to see if any error message is printed.

**Comment by andrucz** [comment]
Please update to v1.1.0.

**Comment by jyj545** [comment]
i have updated it to v1.1.0,but this issues seems still exsiting.
does any code changed in ionic-native?

**Comment by andrucz** [comment]
Strange. I've tested v1.1.0 and everything was fine. Have you seen browser console? Maybe some error is thrown in onModelChange or onKeyDownChange.

**Comment by jyj545** [comment]
yes,i have checked the console, but no error thrown out when i click the rating star.

**Comment by andrucz** [comment]
Could you please share your .ts file?

**Comment by jyj545** [comment]
please show me your email address

**Comment by andrucz** [comment]
andrucz@gmail.com

**Comment by jyj545** [comment]
Thank you very much for your generous help,its working now!

**Comment by andrucz** [comment]
I am glad it worked. You're welcome.
