### ISSUE TITLE
Relative urls for stylesUrl templateUrl

### ISSUE THREAD

**Issue by raparlasiva** [andrucz/ionic2-rating#12]
I see that in your source code you have styles and template not defined in a separate file but rather defined them (the template and styles) in the component itself. I like to know if we can use separate files for template and styles and also use scss instead of css

**Comment by andrucz** [comment]
At the time I was implementing that, I couldn't find a way to export html and scss files and make them work inside the host application. I will look again for a way asap.

**Comment by andrucz** [comment]
@raparlasiva did you have any success trying to use separate files for template and styles? I will close this issue because it is not related to the project itself.
