### ISSUE TITLE
default value for dynamically created rating elements

### ISSUE THREAD

**Issue by roydekleijn** [andrucz/ionic2-rating#13]
Hi,

I like to ask how we can set a initial value (1) ? with the following code.
<rating [(ngModel)]="option.key" max="5" name="{{option.key}}"
                ng-init="option.key='1'"></rating>

Note: I generate these elements dynamically, based on REST response.
Note 2: ng-init="option.key='1'" doesn't work... However, it used to work with ionic 1

Roy

**Comment by gerhardx** [comment]
Put initial value on ts file, in your constructor, set the variable to the default value wanted. In your example:

constructor () {
this.option.key = 1;
}

no need for ng-init
