### ISSUE TITLE
Noob Issue

### ISSUE THREAD

**Issue by tayzee** [andrucz/ionic2-rating#14]
Hey,

Probably more of a noob issue than an issue at all, but Ive been playing around with your plugin today and Im having some difficulties.

1. For some reason in my ionic 2 app that im trying to write, the styling that I put in the corresponding scss file to the html file im using never seems to work, hence in this situation, all I get all the time is 5 little stars.

2. I would be grateful if you could help me with the update script?

**Comment by andrucz** [comment]
Hello. Could you please show me your scss and html files? What exactly do you mean by "update script"?

**Comment by tayzee** [comment]
Hi there,

For some reason the plugin wasnt working as it should when i added it to my project. I couldnt select the stars, it was just static for some reason, I have since worked around that.

As for the css, complete noob issue, I changed the name of the page that i was talking about and forgot to update the page-name in the scss file.

Thanks for taking the time to respond.
