### ISSUE TITLE
 component styles with li padding doesn’t work

### ISSUE THREAD

**Issue by cj1240** [andrucz/ionic2-rating#15]
Hey!
  I want to customize component styles with change the scss file , everything is ok but &.rating li padding, No matter how I modify  the padding value ，it’s doesn’t work。 what should I do? I need your help。 Thanks！

**Comment by andrucz** [comment]
Hey, @cj1240 
Could you please show me your template and scss files?

**Comment by cj1240** [comment]
## # **This is my scss files:**
ul {
  padding: 0px;
  &.rating li {
    padding: 1px 1px;
    background: none;
    color: #387ef5;

    ion-icon {
      font-size: 15px;
    }
  }
}


## # **This is my `template:**`
  <rating [(ngModel)]="rate" 
        readOnly="false" 
        max="5" 
        emptyStarIconName="star-outline" 
        halfStarIconName="star-half" 
        starIconName="star" 
        nullable="false" 
        (ngModelChange)="onModelChange($event)"></rating>

**#The problem is no matter how I modify the   &.rating li padding value，it’s doesn’t work:**
  &.rating li {
    padding: 1px 1px;}

  &.rating li {
    padding: 10px 10px;}

 As shown above，when I running, the padding in star,it's look the same style:

**Comment by cj1240** [comment]
## they are the same style：
![image](https://cloud.githubusercontent.com/assets/7079740/23452403/2cd23554-fe9f-11e6-8f6e-4aace37f3728.png)

## but i want to get the following style：
![image](https://cloud.githubusercontent.com/assets/7079740/23452481/6832322a-fe9f-11e6-851c-aa1271ef1baa.png)

## And now I can only modify the value from manually operated,if I delete the padding just like the following pic,I can got the right result (PS: I used the google chrome )

![image](https://cloud.githubusercontent.com/assets/7079740/23452531/a3674218-fe9f-11e6-8700-2e1b4c62033a.png)

**Comment by andrucz** [comment]
It can happen when you change the page name or selector and forget to change it in scss file.

**Comment by andrucz** [comment]
Please also try to add !important on padding value.

**Comment by cj1240** [comment]
@andrucz  Thank you very much!  I got it when I add !important on padding value.It's OK! 
This tool is very easy to use，I will use it in my team! Thanks!!

Best regards!

**Comment by andrucz** [comment]
Thanks, @cj1240 
I am glad to hear that.
