### ISSUE TITLE
How can I capture the value?

### ISSUE THREAD

**Issue by wuilmerj24** [andrucz/ionic2-rating#16]
I'm learning with ionic 2
I'm using typescript

**Comment by andrucz** [comment]
Hello Wuilmer!

Sorry for the late response. Have you managed to do that?

The variable defined on ngModel property is automatically updated when user clicks on a star.

**Comment by andrucz** [comment]
Hello Wuilmer!

Sorry for the late response. Have you managed to do that?

The variable defined on ngModel property is automatically updated when user clicks on a star.
