### ISSUE TITLE
Default rate values in loop

### ISSUE THREAD

**Issue by imokkali** [andrucz/ionic2-rating#17]
<ion-col *ngFor="let item of recipes" width-50
      <ion-item
       <rating
          readOnly="true"
          max="5"
          emptyStarIconName="star-outline"
          halfStarIconName="star-half"
          starIconName="star"
          nullable="false" /rating>
        ion-title{{item.Rate}} /ion-title
      /ion-item>
/ion-col>

I have a code like this. I need to assign {{item.Rate}} value to rating selector for each item in recipes. What should I do?

**Comment by andrucz** [comment]
Hello, @imokkali 

Use ngModel property:

```HTML
<ion-col *ngFor="let item of recipes" width-50>
  <ion-item>
    <rating readOnly="true" [(ngModel)]="item.Rate"></rating>
  </ion-item>
</ion-col>
```

By the way, do you want to create a column for each recipe or an item? In case you want to create an item, just take ngFor out of ion-col and put it on ion-item tag.

**Comment by saidllamasm** [comment]
I just had that concern, thank you @andrucz !
