### ISSUE TITLE
need a rating bar properties

### ISSUE THREAD

**Issue by vishaltechreceptives** [andrucz/ionic2-rating#20]
Hello,

rating bar in i want full star means if i click 1 star it's rating is 1.
need 1 rating for 1 star. is it possible?
any document for that?

**Comment by andrucz** [comment]
Hello, @vishaltechreceptives 
Sorry for the late response. Do you mean a rating bar with only one star? The "max" property defines how many stars should be displayed.

**Comment by andrucz** [comment]
This is an example of a component that declares all available properties.

```html
<rating [(ngModel)]="rate" 
        readOnly="false"
        max="5"
        emptyStarIconName="star-outline"
        halfStarIconName="star-half"
        starIconName="star"
        nullable="false"
        (ngModelChange)="onModelChange($event)">
</rating>
```
