### ISSUE TITLE
How to set rating ?

### ISSUE THREAD

**Issue by rajanshahsa** [andrucz/ionic2-rating#21]
Hello,
I want to set rating in ionic2. when page load I want to fetch the data from server and based on rating received from server I want to display it to user.

Can you please help me in this?

<rating readOnly="false" value="2" max="5" emptyStarIconName="star-outline" halfStarIconName="star-half" starIconName="star" nullable="false"> </rating>

**Note:-** User can't update it.

**Comment by andrucz** [comment]
Hello, @rajanshahsa 
All you have to do is define ngModel property and assign the fetched value to it. If user can't update it, just set readOnly property to true.

**Comment by rajanshahsa** [comment]
@andrucz  Thank you for your answer, Its works after define ngModel property. Sorry I forgot to closed ticket.  and sorry for late reply
