### ISSUE TITLE
Can't set padding for start to zero 

### ISSUE THREAD

**Issue by fedorinoGore** [andrucz/ionic2-rating#22]
I need to show stars as close as possible to each other. But setting padding to 0 is not working as expected. Stars  still have some significant space between.
Is any way to make them stand side by side with 0 pixels margin/padding? 
[](url)

**Comment by andrucz** [comment]
Hello, @fedorinoGore 
Sorry for the late response. Have you tried to apply ```display: inline-block;``` on ```li```?

**Comment by fedorinoGore** [comment]
Thanks! Worked like charm.

**Comment by andrucz** [comment]
That's great, @fedorinoGore
