### ISSUE TITLE
Getting error like rating is not a known element in Ionic2 project

### ISSUE THREAD

**Issue by andaralex** [andrucz/ionic2-rating#23]
Error: Template parse errors:
rating' is not a known element:
. If 'rating' is an Angular component, then verify that it is part of this module.
. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this
 component. ("
 <ion-item>
   <span class="filter_label">Rating</span>
   [ERROR ->]<rating [(ngModel)]="rate" readOnly="false" max="5" emptyStarIconName="star-outline" halfStarIconName"): ng:///G:/development_workspace/mobile_app/project/src/pages/postajob/postajob.html@100:4

**Comment by GaryMeliman** [comment]
Put Ionic2RatingModule on the module of the page where you want to use the ratingbar, like this.
```
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { EvaluacionPage } from './evaluacion';
import { Ionic2RatingModule } from 'ionic2-rating';

@NgModule({
  declarations: [
    EvaluacionPage,
  ],
  imports: [
    IonicPageModule.forChild(EvaluacionPage),
    Ionic2RatingModule
  ],
  exports: [
    EvaluacionPage
  ]
})
export class EvaluacionPageModule {}
```
