### ISSUE TITLE
Marked stars

### ISSUE THREAD

**Issue by mvaipa** [andrucz/ionic2-rating#25]
Hello, I'm using the plugin, but I can not leave a lot of stars marked, what could I be doing wrong? I'm using rate, but it's not right

<rating [(ngModel)]="rate" 
        readOnly="true" 
        rate="2"
        max="5"
        emptyStarIconName="star-outline"
        halfStarIconName="star-half"
        starIconName="star"
        nullable="false"> 
</rating>

**Comment by andrucz** [comment]
Hello, @mvaipa. I don't know exactly what you mean by that. Keep in mind that the count of marked stars reflects the value of rate variable (that you set on ngModel).

**Comment by podisto** [comment]
Hi, u should implement OnInit and set the default values (ie numbers of stars marked you want).
