### ISSUE TITLE
ionic2-rating integration

### ISSUE THREAD

**Issue by trix87** [andrucz/ionic2-rating#30]
Hello,

I am wondering if there is any way of integrating this into google-maps native htmlInfoWindow?
I tried the following but only the rating div is present, the component is not processed so no ul inside.

```
let marker: Marker = params[1];
        let htmlInfoWindow = new HtmlInfoWindow();

        let frame: HTMLElement = document.createElement('div');
        frame.innerHTML = [
          '<h2>'+ marker.get("name") +'</h2>',
          '<rating [(ngModel)]="'+ marker.get("rating") +'" readOnly="true" max="5" emptyStarIconName="star-outline" halfStarIconName="star-half" starIconName="star" nullable="false"></rating>',
          '<a (click)="openPage(TourismRestaurantDetailedPage,'+ marker.get("restaurantId") +' )">Tovább ></a>'
        ].join("");
        htmlInfoWindow.setContent(frame, {
          width: "230px",
          height: "150px",
        });
        htmlInfoWindow.open(marker);
```

**Comment by andrucz** [comment]
Hi @trix87 
I haven't tried that yet. Take a look at the answer to this post: https://stackoverflow.com/questions/43448577/display-custom-tag-in-google-maps-infowindow-angular2#

Consider ionic2-rating as a regular Angular component. Maybe it helps to figure out how to do what you need.

**Comment by trix87** [comment]
Okkey thanks for the info.

Cheers.
