### ISSUE TITLE
Starting with x stars painted

### ISSUE THREAD

**Issue by joancolmenerodev** [andrucz/ionic2-rating#32]
Is there any way to start with for example 3 of 5 stars painteds?

**Comment by andrucz** [comment]
Hey @joancolmenerodev. Sorry for the delay.
Yes, keep in mind that the component presentation reflects `ngModel` value.

Take for example `<rating [(ngModel)]="rate" ... />`. If you assign 3 to `rate` variable, the component will be shown with 3 stars painted.

**Comment by wyklif** [comment]
What about 3.5? as in three and a half stars painted?

**Comment by saidllamasm** [comment]
Hello! I have the same concern, in my case, the most optimal would be to assign the rantig from the view, example:
`<div class="single-university" *ngFor="let University of Universities">
                <ion-grid>
                    <ion-row>
                        <ion-col col-3>
                            <img class="img-circle img-university" [src]="University.imgsrc">
                        </ion-col>
                        <ion-col col-9>
                            <span class="name-university">{{University.name}}</span>
                            <rating  readOnly="true" max="5" emptyStarIconName="star-outline" halfStarIconName="star-half" starIconName="star" nullable="false" (ngModelChange)="changeRating($event)"></rating>
                        </ion-col>
                    </ion-row>
                </ion-grid>
            </div>`

Is this possible to do?

**Comment by saidllamasm** [comment]
I have already solved it with the help of the following comment [https://github.com/andrucz/ionic2-rating/issues/17#issuecomment-294292545)](https://github.com/andrucz/ionic2-rating/issues/17#issuecomment-294292545), Annex source code example:
**Universities.ts**
`this.nearbyUniversities = [
      {
        imgsrc : "http://becas-mexico.mx/wp-content/uploads/2017/10/becas-mexico-itcg-2017-2018.jpg",
        name :"Instituto Tecnológico de Ciudad Guzmán",
        rate : 2,
        id:"3" 
      },
      {
        imgsrc: "https://cdn-az.allevents.in/banners/2ec9e7fae6b19132288b69c8f1d9e5c9",
        name :"Universidad Pedagógica Nacional de Ciudad Guzmán",
        rate : 4,
        id:"4"
      },
      {
        imgsrc: "https://cdn-az.allevents.in/banners/2ec9e7fae6b19132288b69c8f1d9e5c9",
        name :"Universidad Pedagógica Nacional de Ciudad Guzmán",
        rate : 2.5,
        id:"4"
      }
    ];`
**Universities.html**
`<div class="list-universities-nearby">
            <div class="single-university" *ngFor="let nearbyUniversity of nearbyUniversities">
                <ion-grid>
                    <ion-row>
                        <ion-col col-3>
                            <img class="img-circle img-university" [src]="nearbyUniversity.imgsrc">
                        </ion-col>
                        <ion-col col-9>
                            <span class="name-university">{{nearbyUniversity.name}}</span>
                            <rating [(ngModel)]="nearbyUniversity.rate" readOnly="true" max="5" emptyStarIconName="star-outline" halfStarIconName="star-half" starIconName="star" nullable="false" (ngModelChange)="onModelChange($event)"></rating>
                        </ion-col>
                    </ion-row>
                </ion-grid>
            </div>
        </div>`
