### ISSUE TITLE
Im trying to remove padding and margin.

### ISSUE THREAD

**Issue by mrizwan2018** [andrucz/ionic2-rating#33]
Im trying to remove padding and margin but unable to do that,

**Comment by andrucz** [comment]
Hey, @mrizwan2018. Sorry for the delay.
Could you please show me what CSS definitions have you created?

**Comment by andrucz** [comment]
Example from the docs:

```
ul {
  padding: 0px;

  &.rating li {
    padding: 5px 10px !important;
  }
}
```
