### ISSUE TITLE
no half start 

### ISSUE THREAD

**Issue by adongroom** [andrucz/ionic2-rating#35]

**Comment by andrucz** [comment]
Could you please throw some light on that? What are you trying to do and what problem are you facing?

**Comment by rayonx** [comment]
I think OP is trying to say "No half stars" in the title. It was a typo I assume.

**Comment by erikramalho** [comment]
I think he meant he would like to avoid half stars. BTW is there any way? I need it to.

**Comment by andrucz** [comment]
Yes, keep in mind that any value with decimals will result in a half star icon. You just need to round the value.

**Comment by andrucz** [comment]
Also, always when user selects a star, value should have no decimals.
