### ISSUE TITLE
Does not work when I click in the same start

### ISSUE THREAD

**Issue by davidcm86** [andrucz/ionic2-rating#36]
Hello!

When I click in the same star that I did, event is empty and not recive the star value.  ¿Is there something wrong?

Thx!!

**Comment by andrucz** [comment]
Hello, @davidcm86 
The component actually prevents the event from being fired when the value is not changed (click on the same star, for example). If you need to clear the selection when the user clicks on the same star, the `nullable` property must be set to `true`. Depending on what you need, we may create another event, which will be fired whenever a user clicks on any star.

**Comment by davidcm86** [comment]
@andrucz , I set nullable true but then, when I click in the same star, my [(ngModel)]="rate" in the component is null....other star I recive the rate ok, but not the same star. Any idea?

**Comment by andrucz** [comment]
That's exactly what `nullable` property does. It has been created to clear the value when a user clicks on the same star. Could you please throw some light on what exactly you want to happen in this case?

**Comment by davidcm86** [comment]
Ok. I print my view with your rating module, when I click on the star I recive the rate in a function and then I sent new data into the same view and this is my stuck, because if I want to vote the same star, the rate is always null and the event never come.

**Comment by andrucz** [comment]
You can keep track of the selected value with the variable associated with `ngModel` property.

`ngModelChange` is invoked whenever the user actually changes the value (which doesn't happen when he clicks on the same star).

I believe the best solution would implement another event to be called every time a star is clicked. As a workaround, enable the `nullable` property and when `ngModelChange` is invoked with a null value, set the rate to the last selected value (a second variable will be required to do this).

**Comment by davidcm86** [comment]
Thank you andrucz. It is works fine with your solution.
Regards and thx for the module!

**Comment by andrucz** [comment]
I am glad to hear that!
I will soon implement that new event, so that workaround will no longer be required.
