### ISSUE TITLE
Getting error module not found

### ISSUE THREAD

**Issue by kanishkamehta20** [andrucz/ionic2-rating#37]
Hello Team 

I had followed the complete steps mentioned but i am getting en error, please help me to get rid of this problem.

Error:
ERROR in ./node_modules/ionic2-rating/dist/ionic2-rating.module.js
Module not found: Error: Can't resolve 'ionic-angular' in '/Users/kanishka/Desktop/starrating/node_modules/ionic2-rating/dist'

Thanks in advance.

**Comment by andrucz** [comment]
Hey, @kanishkamehta20 
It seems like your project doesn't have a reference to "ionic-angular". Have you run npm install? If so, could you please share your package.json file?
