### ISSUE TITLE
Can I do a loop?

### ISSUE THREAD

**Issue by davidcm86** [andrucz/ionic2-rating#39]
Hello again andrucz!

First of all, sorry if my question is a question from newbie in angular/ionic, because I am.
I want to do a loop with your module, but it does not work for me, because here [(ngModel)]="rate" it's like that only works once and only could receive this.rate once from component. Is that true or there is other way?

I have an array with several rating.

Thank a lot!!

**Comment by andrucz** [comment]
Hello @davidcm86 
In this case, you need one ngModel variable for each rating component.

`<rating *ngFor="let item of items" [(ngModel)]="item.rate" ...>`, for example

**Comment by andrucz** [comment]
Using an array of ratings:

`<rating *ngFor="let rate of rates; let i = index" [(ngModel)]="rates[i]" ...>`

**Comment by davidcm86** [comment]
OMG, I did that without item, only rate....my mistake. Sorry about that. 
Thank a lot!
