### ISSUE TITLE
Doesn't work with ngFor

### ISSUE THREAD

**Issue by timsergeev** [andrucz/ionic2-rating#41]
Hi there..

Tried to use this module inside the loop. But can't assign variable via ngModel. Probably I am missing something. How to use multiple readonly instances of this module?

**Comment by ferrGruppoBs** [comment]
I have the same problem, this plug in is still supported?

Thank you

**Comment by ferrGruppoBs** [comment]
Sorry, it works correctly, my error in the model.

[(NgModel)] = "item.Rate"
