### ISSUE TITLE
rating is not a known element

### ISSUE THREAD

**Issue by ManojGaru** [andrucz/ionic2-rating#43]
<ion-card padding>
    		<ion-card [(ngModel)]="rate" max="5" emptyStarIconName="star-outline" halfStarIconName="star-half" starIconName="star" nullable="false" (ngModelChange)="onModelChange($event)">
      
    </ion-card>
    		<h2>{{rate}}</h2>
    
  </ion-card>

**Comment by andrucz** [comment]
Feel free to reopen this issue in case the problem persists
