### ISSUE TITLE
Won't work with Ionic 4

### ISSUE THREAD

**Issue by matheusdavidson** [andrucz/ionic2-rating#44]
The plugin won't work with ionic 4:
```bash
[ng] ERROR in ./node_modules/ionic2-rating/dist/ionic2-rating.module.js
[ng] Module not found: Error: Can't resolve 'ionic-angular' in '/private/var/www/youchange/hibrido/node_modules/ionic2-rating/dist'
```

The solution is to change:
```typescript
import { IonicModule } from 'ionic-angular';
```

for:
```typescript
import { IonicModule } from '@ionic/angular';
```

**Comment by BahgatMashaly** [comment]
any updates ?

**Comment by Amadorval75** [comment]
Nothing yet?.

Still not working for me on ionic 4.

**Comment by andrucz** [comment]
Sorry guys. I no longer use Ionic and don't have enough free time to check the issues of this project. If anyone can take this issue, I'd appreciate it.

**Comment by nathanpronto** [comment]
Hey @andrucz , I can help you with that.. just never contributed to an open source before. I'd be happy to do it, though. Can you guide me?

**Comment by remisture** [comment]
I need this to work with Ionic 4. Anyone?

**Comment by matheusdavidson** [comment]
Make the changes manually in node_modules or fork the project, change and use that

**Comment by lincond** [comment]
I updated an Ionic 3 rating component to Ionic 4. Here's the [npm](https://www.npmjs.com/package/ionic4-rating) link.
