### ISSUE TITLE
Changing the star icon in ionic2-rating plugin

### ISSUE THREAD

**Issue by Divyea** [andrucz/ionic2-rating#45]
Hi, i am working on rating functionality i have added ionic2-rating plugin it worked fine. But i want add my own svg image in the place of star for the below code, How can i achieve this?  

<rating [(ngModel)]="rate" 
        readOnly="false" 
        max="5"
        emptyStarIconName="star-outline"
        halfStarIconName="star-half"
        starIconName="star" 
        nullable="false" 
        (ngModelChange)="onModelChange($event)"> 
</rating>

**Comment by andrucz** [comment]
You need to create custom Ionicons icons, and then replace `star-outline` and `star-half` with their names.
