### ISSUE TITLE
padding in li not change

### ISSUE THREAD

**Issue by nooralsbah** [andrucz/ionic2-rating#5]
Hi
when I'm trying to change padding on the li nothing happens.
any help ..
Thanks

**Comment by andrucz** [comment]
hi. could you please show me how are you trying to do that?

**Comment by pdorney** [comment]
Hi

Is it possible to add a border color to the Stars? trying using border but not having any luck.

**Comment by chocopoule** [comment]
I had the same padding problem and solved it using !important:

```
ul {
  padding: 0px;

  &.rating li {
    padding: 1px 1px !important;
    background: none;
    color: #ffb400;

    ion-icon {
      font-size: 30px;
    }
  }
}
```

**Comment by andrucz** [comment]
@nooralsbah could you please show me how are you trying to do that?

@pdorney do you want to add a border around every star separately or around the entire container?
