### ISSUE TITLE
Delay when stars tapped on ios

### ISSUE THREAD

**Issue by willynilly** [andrucz/ionic2-rating#6]
I'm noticing a click delay when tapping a star on iOS.  Do you think you need to add a "tappable" attribute on the stars markup?  http://ionicframework.com/docs/v2/faq/#click-delays

**Comment by willynilly** [comment]
I created a pull request that seems to fix this issue: https://github.com/andrucz/ionic2-rating/pull/7

**Comment by andrucz** [comment]
I don't have an iOS device to test it (I would have to sell a kidney to buy one here in Brazil lol), but that makes sense. Thank you!
