### ISSUE TITLE
Compatibility Issue with karma-typescript

### ISSUE THREAD

**Issue by willynilly** [andrucz/ionic2-rating#8]
After following this tutorial:

http://www.joshmorony.com/how-to-unit-test-an-ionic-2-application/

 Karma appears to complain about how ionic2-rating uses an "Uncaught SyntaxError: Unexpected token export".

Using awk, I examined the giant karma bundle file, and traced down the error to this:

"node_modules/ionic2-rating/index.js']=[function(require,module,exports,__dirname,__filename){ export { Ionic2RatingModule } from './module';"

 I suspect this is because the ionic2-rating distribution code is compiled to ES6, and the unknown token is "export".  Can you recompile the code to ES5 so that it will play nicely with karma and other test runners?

**Comment by andrucz** [comment]
Hello, @willynilly  

Are you using the latest version? If so, could you please try 0.0.10 version? I've made some changes recently in `tsconfig.json` file (but target is still `es5`).

**Comment by andrucz** [comment]
Please update to v1.1.0 and see if the problem still occurs.
