### ISSUE TITLE
question, how to register a change callback

### ISSUE THREAD

**Issue by mrbase** [andrucz/ionic2-rating#9]
I'm pretty new to ionic and angular and have a hard time figuring out how to detect changes when the ratings are changed.

I have the ratings displayed, and changing the votes works, but how to detect the change for later use ?

**Comment by andrucz** [comment]
Hello, @mrbase 

It is possible with `ngModelChange` event:

`<rating [(ngModel)]="rate" (ngModelChange)="onRateChange($event)"></rating>`

Then in `onRateChange` function you can access rating value through `$event` parameter or through `rate `property.

Hope it helps.

**Comment by mrbase** [comment]
excellent @andrucz thanks :)
